"""Tool categories and definitions for katoolin3.

All Kali Linux tools organized into 14 categories.
Each tool is a string representing the apt package name.
"""

CATEGORIES = {
    1: {
        "name": "Information Gathering",
        "tools": [
            "acccheck",
            "ace-voip",
            "amap",
            "automater",
            "bing-ip2hosts",
            "braa",
            "casefile",
            "cdpsnarf",
            "cisco-torch",
            "cookie-cadger",
            "copy-router-config",
            "dmitry",
            "dnmap",
            "dnsenum",
            "dnsmap",
            "dnsrecon",
            "dnstracer",
            "dnswalk",
            "dotdotpwn",
            "enum4linux",
            "enumiax",
            "exploitdb",
            "fierce",
            "firewalk",
            "fragroute",
            "fragrouter",
            "ghost-phisher",
            "golismero",
            "goofile",
            "hping3",
            "intrace",
            "ismtp",
            "lbd",
            "maltego-teeth",
            "masscan",
            "metagoofil",
            "miranda",
            "nbtscan-unixwiz",
            "nmap",
            "p0f",
            "parsero",
            "recon-ng",
            "set",
            "smtp-user-enum",
            "snmpcheck",
            "sslcaudit",
            "sslsplit",
            "sslstrip",
            "sslyze",
            "thc-ipv6",
            "theharvester",
            "tlssled",
            "twofi",
            "urlcrazy",
            "wireshark",
            "wol-e",
            "xplico",
        ],
    },
    2: {
        "name": "Vulnerability Analysis",
        "tools": [
            "bbqsql",
            "bed",
            "cisco-auditing-tool",
            "cisco-global-exploiter",
            "cisco-ocs",
            "cisco-torch",
            "commix",
            "copy-router-config",
            "doona",
            "dotdotpwn",
            "greenbone-security-assistant",
            "gsd",
            "hexorbase",
            "jsql",
            "lynis",
            "nmap",
            "ohrwurm",
            "openvas-cli",
            "openvas-manager",
            "openvas-scanner",
            "oscanner",
            "powerfuzzer",
            "sfuzz",
            "sidguesser",
            "siparmyknife",
            "sqlmap",
            "sqlninja",
            "sqlsus",
            "thc-ipv6",
            "tnscmd10g",
            "unix-privesc-check",
            "yersinia",
        ],
    },
    3: {
        "name": "Wireless Attacks",
        "tools": [
            "aircrack-ng",
            "asleap",
            "bluelog",
            "bluemaho",
            "bluepot",
            "blueranger",
            "bluesnarfer",
            "bully",
            "cowpatty",
            "crackle",
            "eapmd5pass",
            "fern-wifi-cracker",
            "ghost-phisher",
            "giskismet",
            "gqrx",
            "gr-scan",
            "hostapd-wpe",
            "kalibrate-rtl",
            "killerbee",
            "kismet",
            "mdk3",
            "mfcuk",
            "mfoc",
            "mfterm",
            "multimon-ng",
            "pixiewps",
            "reaver",
            "redfang",
            "rtlsdr-scanner",
            "spooftooph",
            "wifi-honey",
            "wifiphisher",
            "wifitap",
            "wifite",
        ],
    },
    4: {
        "name": "Web Applications",
        "tools": [
            "apache-users",
            "arachni",
            "bbqsql",
            "blindelephant",
            "burpsuite",
            "commix",
            "cutycapt",
            "davtest",
            "deblaze",
            "dirb",
            "dirbuster",
            "fimap",
            "funkload",
            "gobuster",
            "grabber",
            "jboss-autopwn",
            "joomscan",
            "jsql",
            "maltego-teeth",
            "padbuster",
            "paros",
            "parsero",
            "plecost",
            "powerfuzzer",
            "proxystrike",
            "recon-ng",
            "skipfish",
            "sqlmap",
            "sqlninja",
            "sqlsus",
            "ua-tester",
            "uniscan",
            "vega",
            "w3af",
            "webscarab",
            "webslayer",
            "websploit",
            "wfuzz",
            "wpscan",
            "xsser",
            "zaproxy",
        ],
    },
    5: {
        "name": "Sniffing & Spoofing",
        "tools": [
            "burpsuite",
            "dnschef",
            "fiked",
            "hamster-sidejack",
            "hexinject",
            "iaxflood",
            "inviteflood",
            "ismtp",
            "isr-evilgrade",
            "mitmproxy",
            "ohrwurm",
            "protos-sip",
            "rebind",
            "responder",
            "rtpbreak",
            "rtpinsertsound",
            "rtpmixsound",
            "sctpscan",
            "siparmyknife",
            "sipp",
            "sipvicious",
            "sniffjoke",
            "sslsplit",
            "sslstrip",
            "thc-ipv6",
            "voiphopper",
            "webscarab",
            "wifi-honey",
            "wireshark",
            "xspy",
            "yersinia",
            "zaproxy",
        ],
    },
    6: {
        "name": "Maintaining Access",
        "tools": [
            "cryptcat",
            "cymothoa",
            "dbd",
            "dns2tcp",
            "http-tunnel",
            "httptunnel",
            "intersect",
            "nishang",
            "polenum",
            "powersploit",
            "pwnat",
            "ridenum",
            "sbd",
            "u3-pwn",
            "webshells",
            "weevely",
            "winexe",
        ],
    },
    7: {
        "name": "Reporting Tools",
        "tools": [
            "casefile",
            "cutycapt",
            "dos2unix",
            "dradis",
            "keepnote",
            "magictree",
            "metagoofil",
            "nipper-ng",
            "pipal",
        ],
    },
    8: {
        "name": "Exploitation Tools",
        "tools": [
            "armitage",
            "backdoor-factory",
            "beef-xss",
            "cisco-auditing-tool",
            "cisco-global-exploiter",
            "cisco-ocs",
            "cisco-torch",
            "commix",
            "crackle",
            "exploitdb",
            "jboss-autopwn",
            "linux-exploit-suggester",
            "maltego-teeth",
            "set",
            "shellnoob",
            "sqlmap",
            "thc-ipv6",
            "yersinia",
        ],
    },
    9: {
        "name": "Forensics Tools",
        "tools": [
            "binwalk",
            "bulk-extractor",
            "capstone",
            "chntpw",
            "cuckoo",
            "dc3dd",
            "ddrescue",
            "distorm3",
            "dumpzilla",
            "extundelete",
            "foremost",
            "galleta",
            "guymager",
            "iphone-backup-analyzer",
            "p0f",
            "pdf-parser",
            "pdfid",
            "pdgmail",
            "peepdf",
            "python-distorm3",
            "volatility",
            "xplico",
        ],
    },
    10: {
        "name": "Stress Testing",
        "tools": [
            "dhcpig",
            "funkload",
            "iaxflood",
            "inundator",
            "inviteflood",
            "ipv6-toolkit",
            "mdk3",
            "reaver",
            "rtpflood",
            "slowhttptest",
            "t50",
            "termineter",
            "thc-ipv6",
            "thc-ssl-dos",
        ],
    },
    11: {
        "name": "Password Attacks",
        "tools": [
            "acccheck",
            "burpsuite",
            "cewl",
            "chntpw",
            "cisco-auditing-tool",
            "cmospwd",
            "creddump",
            "crunch",
            "dbpwaudit",
            "findmyhash",
            "gpp-decrypt",
            "hash-identifier",
            "hexorbase",
            "hydra",
            "john",
            "johnny",
            "keimpx",
            "maltego-teeth",
            "maskprocessor",
            "multiforcer",
            "ncrack",
            "oclgausscrack",
            "pack",
            "patator",
            "polenum",
            "rainbowcrack",
            "rcracki-mt",
            "rsmangler",
            "statsprocessor",
            "thc-pptp-bruter",
            "truecrack",
            "webscarab",
            "wordlists",
            "zaproxy",
        ],
    },
    12: {
        "name": "Reverse Engineering",
        "tools": [
            "apktool",
            "dex2jar",
            "python-distorm3",
            "edb-debugger",
            "jad",
            "javasnoop",
            "smali",
            "valgrind",
            "yara",
        ],
    },
    13: {
        "name": "Hardware Hacking",
        "tools": [
            "android-sdk",
            "apktool",
            "arduino",
            "dex2jar",
            "sakis3g",
            "smali",
        ],
    },
    14: {
        "name": "Extra",
        "tools": [
            "kali-linux",
            "kali-linux-full",
            "kali-linux-all",
            "kali-linux-top10",
            "kali-linux-forensic",
            "kali-linux-gpu",
            "kali-linux-pwtools",
            "kali-linux-rfid",
            "kali-linux-sdr",
            "kali-linux-voip",
            "kali-linux-web",
            "kali-linux-wireless",
            "squid3",
        ],
    },
}


def get_tool_name(tool):
    """Get display name from a tool entry."""
    return tool


def get_category_names():
    """Return dict of {id: name} for all categories."""
    return {k: v["name"] for k, v in CATEGORIES.items()}


def get_tools(category_id):
    """Return list of tools for a category."""
    return CATEGORIES[category_id]["tools"]


def count_all_tools():
    """Return total number of tools across all categories."""
    return sum(len(c["tools"]) for c in CATEGORIES.values())
